volumes:
  uploads:

networks:
  vchat_network:
    driver: bridge
    name: vchat_network

services:
  vchat_postgres:
    container_name: vchat_postgres
    build:
      context: ./docker/postgres
    environment:
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data/pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - vchat_network

  api_server:
    build:
      context: server/
      dockerfile: ${NODE_ENV:-prod}.Dockerfile
    restart: unless-stopped
    depends_on:
      - vchat_postgres
    environment:
      - NODE_ENV=${NODE_ENV:-prod}
      - ANNOUNCED_IP=${ANNOUNCED_IP}
      - ROOMS_LIST=${ROOMS_LIST}
      - MEDIASOUP_MIN_PORT=${MEDIASOUP_MIN_PORT}
      - MEDIASOUP_MAX_PORT=${MEDIASOUP_MAX_PORT}
      - REACT_APP_CLIENT_VERSION=${REACT_APP_CLIENT_VERSION}
      - SERVER_VERSION=${SERVER_VERSION}
      - DB_HOST=vchat_postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./server:/app
      - /app/node_modules
      - uploads:/app/uploads
    ports:
      - "8081:8081"
      - "${MEDIASOUP_MIN_PORT}-${MEDIASOUP_MAX_PORT}:${MEDIASOUP_MIN_PORT}-${MEDIASOUP_MAX_PORT}"
    networks:
      - vchat_network

  frontend:
    image: nginx:1.29.3
    restart: unless-stopped
    environment:
      - APP_DOMAIN=${REACT_APP_DOMAIN}
      - NGINX_CONFIG_FILE=${NGINX_CONFIG_FILE}
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/prod.default.conf.template:/etc/nginx/conf.d/prod.default.conf.template
      - ./docker/nginx/dev.default.conf.template:/etc/nginx/conf.d/dev.default.conf.template
      - ./docker/nginx/entrypoint.sh:/docker-entrypoint.sh
      - ./build:/var/www/html
      - uploads:/var/www/html/uploads
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/certbot/conf:/etc/nginx/ssl
    entrypoint: [ "/bin/sh", "/docker-entrypoint.sh" ]
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api_server
    networks:
      - vchat_network

  npm:
    image: node:20.17
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - "./:/var/www/html"

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/certbot/www/:/var/www/certbot/
      - ./docker/certbot/conf/:/etc/letsencrypt/
