server {
    listen 80;
    server_name vchat.the-notebook.ru; # vchat.the-notebook.ru
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Надо закомментить весь этот блок для первого получения SSL
    location / {
        return 301 https://vchat.the-notebook.ru; # vchat.the-notebook.ru
    }
}

# Надо закомментить весь этот блок для первого получения SSL
server {
    listen 80;
    server_name 87.251.87.161; # IP 87.251.87.161
    return 301 https://vchat.the-notebook.ru; # vchat.the-notebook.ru
}

server {
    client_max_body_size 128M;
    listen 443 ssl; # для первого получения SSL надо сделать тут listen 80
    server_name vchat.the-notebook.ru; # vchat.the-notebook.ru
    ssl_certificate /etc/nginx/ssl/live/vchat.the-notebook.ru/fullchain.pem; # для первого получения SSL закомментить сроку
    ssl_certificate_key /etc/nginx/ssl/live/vchat.the-notebook.ru/privkey.pem; # для первого получения SSL закомментить сроку

    location / {
        root /var/www/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

     # WebSocket
    location /ws {
        proxy_pass http://web:8080/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_buffering off;
    }

    error_log /var/log/nginx/vchat_error.log;
    access_log /var/log/nginx/vchat_access.log;
}